sudo: false
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
script:
  - node --version
  - npm --version
  - npx --version
  - npm test
after_test:
  - npx codecov
